name: lfs-cache

on:
  schedule:
    - cron: "0 0 1,7,13,20,26 * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-2022
    steps:
      - uses: nschloe/action-cached-lfs-checkout@f46300cd8952454b9f0a21a3d133d4bd5684cfc2 # v1.2.3
