name: lfs-cache

on:
  schedule:
    - cron: "0 0 1,7,13,20,26 * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-2022
    steps:
      - uses: n-air-app/action-cached-lfs-checkout@6def4ea51ae9d33a76cdde8af51210625123d96e # hash-pinning対応版
