name: test

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - 'rollup.config.mjs'
      - 'src/**'
      - 'n-voice/**'
      - '.github/workflows/test.yml'
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - 'rollup.config.mjs'
      - 'src/**'
      - 'n-voice/**'
      - '.github/workflows/test.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-2022
    steps:
    - uses: n-air-app/action-cached-lfs-checkout@f46300cd8952454b9f0a21a3d133d4bd5684cfc2 # hash-pinning対応版

    - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install
      run: npm install

    - name: build test (for Syntax check)
      run: |
        npm run build
